### ISSUE TITLE
VLAN Tag ID, line wrap

### ISSUE THREAD

**Issue by mazhead** [chmod666org/lsseas#1]
On adapters with big number of VLAN TAG's the line wrap creates a issue.

Entstat example (note the new line wrap for 221 and 222):

VLAN Tag IDs:   144   145   150   151   200   202   204   206   220
                221   222

Script output:
vlan_tags_ids                      
-------------                      
144,145,150,151,200,202,204,206,220

Did not find a way how to fix this so far.

**Comment by chmod666org** [comment]
Hi,Thanks for you support. I'm working on this issue right now and will commit the last version with this bug corrected tonight. Regards, B. 
      De : mazhead <notifications@github.com>
 À : chmod666org/lsseas <lsseas@noreply.github.com> 
 Envoyé le : Mardi 3 mars 2015 16h55
 Objet : [lsseas] VLAN Tag ID, line wrap (#1)
   
On adapters with big number of VLAN TAG's the line wrap creates a issue.Entstat example (note the new line wrap for 221 and 222):VLAN Tag IDs: 144 145 150 151 200 202 204 206 220
 221 222Script output:
vlan_tags_ids 
144,145,150,151,200,202,204,206,220Did not find a way how to fix this so far.—

**Comment by chmod666org** [comment]
Corrected in version 0.1b. It is ok now. Closing the issue.
Thanks for you support.
